# Gunakan image PostgreSQL dengan TimescaleDB dari Docker Hub
FROM timescale/timescaledb:latest-pg17

# Set environment variables untuk konfigurasi PostgreSQL
ENV POSTGRES_USER=myuser
ENV POSTGRES_PASSWORD=mypassword
ENV POSTGRES_DB=mydatabase

# Expose port default PostgreSQL
EXPOSE 5432
